-- MySQL Script generated by MySQL Workbench
-- Tue Apr 25 16:39:53 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema projetfinal
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `projetfinal` ;

-- -----------------------------------------------------
-- Schema projetfinal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetfinal` DEFAULT CHARACTER SET utf8 ;
USE `projetfinal` ;

-- -----------------------------------------------------
-- Table `projetfinal`.`utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetfinal`.`utilisateur` ;

CREATE TABLE IF NOT EXISTS `projetfinal`.`utilisateur` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetfinal`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetfinal`.`role` ;

CREATE TABLE IF NOT EXISTS `projetfinal`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetfinal`.`utilisateur_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetfinal`.`utilisateur_role` ;

CREATE TABLE IF NOT EXISTS `projetfinal`.`utilisateur_role` (
  `utilisateur_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`utilisateur_id`, `role_id`),
  CONSTRAINT `fk_utilisateur_has_role_utilisateur`
    FOREIGN KEY (`utilisateur_id`)
    REFERENCES `projetfinal`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateur_has_role_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `projetfinal`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_utilisateur_has_role_role1_idx` ON `projetfinal`.`utilisateur_role` (`role_id` ASC);

CREATE INDEX `fk_utilisateur_has_role_utilisateur_idx` ON `projetfinal`.`utilisateur_role` (`utilisateur_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
