-- MySQL Script generated by MySQL Workbench
-- Thu Apr 13 15:30:21 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Projetcommsimplon
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Projetcommsimplon` ;

-- -----------------------------------------------------
-- Schema Projetcommsimplon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Projetcommsimplon` DEFAULT CHARACTER SET utf8 ;
USE `Projetcommsimplon` ;

-- -----------------------------------------------------
-- Table `Projetcommsimplon`.`promo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Projetcommsimplon`.`promo` ;

CREATE TABLE IF NOT EXISTS `Projetcommsimplon`.`promo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `date_debut` DATE NOT NULL,
  `date_fin` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projetcommsimplon`.`utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Projetcommsimplon`.`utilisateur` ;

CREATE TABLE IF NOT EXISTS `Projetcommsimplon`.`utilisateur` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `mot_de_passe` VARCHAR(45) NOT NULL,
  `mail_perso` VARCHAR(45) NOT NULL,
  `mail_responsable` VARCHAR(45) NULL,
  `promo_id` INT NOT NULL,
  `utilisateur_id` INT NOT NULL,
  PRIMARY KEY (`id`, `promo_id`, `utilisateur_id`),
  CONSTRAINT `fk_utilisateur_promo1`
    FOREIGN KEY (`promo_id`)
    REFERENCES `Projetcommsimplon`.`promo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateur_utilisateur1`
    FOREIGN KEY (`utilisateur_id`)
    REFERENCES `Projetcommsimplon`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_utilisateur_promo1_idx` ON `Projetcommsimplon`.`utilisateur` (`promo_id` ASC);

CREATE INDEX `fk_utilisateur_utilisateur1_idx` ON `Projetcommsimplon`.`utilisateur` (`utilisateur_id` ASC);


-- -----------------------------------------------------
-- Table `Projetcommsimplon`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Projetcommsimplon`.`role` ;

CREATE TABLE IF NOT EXISTS `Projetcommsimplon`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projetcommsimplon`.`role_utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Projetcommsimplon`.`role_utilisateur` ;

CREATE TABLE IF NOT EXISTS `Projetcommsimplon`.`role_utilisateur` (
  `role_id` INT NOT NULL,
  `utilisateur_id` INT NOT NULL,
  PRIMARY KEY (`role_id`, `utilisateur_id`),
  CONSTRAINT `fk_role_has_utilisateur_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `Projetcommsimplon`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_has_utilisateur_utilisateur1`
    FOREIGN KEY (`utilisateur_id`)
    REFERENCES `Projetcommsimplon`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_role_has_utilisateur_utilisateur1_idx` ON `Projetcommsimplon`.`role_utilisateur` (`utilisateur_id` ASC);

CREATE INDEX `fk_role_has_utilisateur_role_idx` ON `Projetcommsimplon`.`role_utilisateur` (`role_id` ASC);


-- -----------------------------------------------------
-- Table `Projetcommsimplon`.`session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Projetcommsimplon`.`session` ;

CREATE TABLE IF NOT EXISTS `Projetcommsimplon`.`session` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `date_debut` DATE NOT NULL,
  `date_fin` DATE NOT NULL,
  `promo_id` INT NOT NULL,
  PRIMARY KEY (`id`, `promo_id`),
  CONSTRAINT `fk_session_promo1`
    FOREIGN KEY (`promo_id`)
    REFERENCES `Projetcommsimplon`.`promo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_session_promo1_idx` ON `Projetcommsimplon`.`session` (`promo_id` ASC);


-- -----------------------------------------------------
-- Table `Projetcommsimplon`.`evenement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Projetcommsimplon`.`evenement` ;

CREATE TABLE IF NOT EXISTS `Projetcommsimplon`.`evenement` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_debut` DATE NOT NULL,
  `date_fin` VARCHAR(45) NOT NULL,
  `description` LONGTEXT NULL,
  `promo_id` INT NOT NULL,
  PRIMARY KEY (`id`, `promo_id`),
  CONSTRAINT `fk_evenement_promo1`
    FOREIGN KEY (`promo_id`)
    REFERENCES `Projetcommsimplon`.`promo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_evenement_promo1_idx` ON `Projetcommsimplon`.`evenement` (`promo_id` ASC);


-- -----------------------------------------------------
-- Table `Projetcommsimplon`.`type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Projetcommsimplon`.`type` ;

CREATE TABLE IF NOT EXISTS `Projetcommsimplon`.`type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projetcommsimplon`.`commentaire`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Projetcommsimplon`.`commentaire` ;

CREATE TABLE IF NOT EXISTS `Projetcommsimplon`.`commentaire` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` LONGTEXT NOT NULL,
  `type_id` INT NOT NULL,
  `session_id` INT NOT NULL,
  `utilisateur_id` INT NOT NULL,
  PRIMARY KEY (`id`, `type_id`, `session_id`, `utilisateur_id`),
  CONSTRAINT `fk_commentaire_session1`
    FOREIGN KEY (`session_id`)
    REFERENCES `Projetcommsimplon`.`session` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commentaire_type1`
    FOREIGN KEY (`type_id`)
    REFERENCES `Projetcommsimplon`.`type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commentaire_utilisateur1`
    FOREIGN KEY (`utilisateur_id`)
    REFERENCES `Projetcommsimplon`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_commentaire_session1_idx` ON `Projetcommsimplon`.`commentaire` (`session_id` ASC);

CREATE INDEX `fk_commentaire_type1_idx` ON `Projetcommsimplon`.`commentaire` (`type_id` ASC);

CREATE INDEX `fk_commentaire_utilisateur1_idx` ON `Projetcommsimplon`.`commentaire` (`utilisateur_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
